app:
  version : '@project.version@'

server:
  port: 8096
  servlet:
   context-path: /student


spring:
  datasource:
    url: jdbc:mysql://rec-student.cc8ui9o8cgvn.us-east-2.rds.amazonaws.com:3306/rec_student?autoReconnect=true
    username: admin
    password: sairam98
    #url: jdbc:mysql://localhost:3306/rec_student?autoReconnect=true
    #username: root
    #password: root
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
     # ddl-auto: create
      generate-ddl: true




timeZone: "Asia/Kolkata"

passwordResetMail:
  body: 'To complete the password reset process, please click here: '

configKeys:
  versionKey: 'MINIMUM_REQUIRED_VERSION'

